allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.24 || 4.0.30 || 4.0.31 || 4.0.32 || 4.0.54'
  - '@ai-sdk/openai-compatible@3.0.13 || 3.0.16 || 3.0.17'
  - '@ai-sdk/vue@4.0.32 || 4.0.40 || 4.0.41 || 4.0.42 || 4.0.68'
  - '@ai-sdk/xai@4.0.17 || 4.0.20 || 4.0.21 || 4.0.22'
  - ai@7.0.32 || 7.0.40 || 7.0.41 || 7.0.42 || 7.0.68
  - '@iconify-json/lucide@1.2.120 || 1.2.124 || 1.2.132'
  - '@ai-sdk/provider-utils@5.0.14 || 5.0.15'
  - '@ai-sdk/provider@4.0.4'
  - '@nuxt/kit@4.5.1'
  - '@nuxt/nitro-server@4.5.1'
  - '@nuxt/schema@4.5.1'
  - '@nuxt/vite-builder@4.5.1'
  - nuxt@4.5.1
  - '@vueuse/core@14.4.0'
  - '@vueuse/metadata@14.4.0'
  - '@vueuse/nuxt@14.4.0'
  - '@vueuse/shared@14.4.0'
  - zod@4.6.4 || 4.6.5
  - autoprefixer@10.6.0
  - '@tybys/wasm-util@0.10.4'
  - ansis@4.4.0
  - enhanced-resolve@5.25.1
